# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup_card',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseEntity')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('tag', models.ManyToManyField(to='base.Tag_general')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Type_general')),
            ],
            bases=('base.baseentity', models.Model),
        ),
        migrations.CreateModel(
            name='Popup_card_catalog',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseEntity')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('card', models.ManyToManyField(to='popup_card.Popup_card')),
                ('tag', models.ManyToManyField(to='base.Tag_general')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Type_general')),
            ],
            bases=('base.baseentity', models.Model),
        ),
        migrations.CreateModel(
            name='Price_popup_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(verbose_name='Init Price')),
                ('end_date', models.DateTimeField(verbose_name='Finish Price')),
                ('price', models.DecimalField(decimal_places=5, max_digits=21)),
                ('percentage_discount', models.SmallIntegerField(null=True)),
                ('quantity_discount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Status_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='price_popup_card',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup_card.Status_price'),
        ),
    ]
