# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_card', '0002_popup_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup_card',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
