# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_card', '0004_auto_20170916_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup_card',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
