# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup_card', '0006_auto_20170916_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup_card',
            options={'ordering': ('create_date',)},
        ),
    ]
