# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170915_2118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popup_card', '0007_auto_20170923_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseEntity')),
                ('content', models.TextField()),
                ('commend_related', models.BigIntegerField(null=True)),
                ('is_reply', models.BooleanField(default=True)),
            ],
            bases=('base.baseentity', models.Model),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_like', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='popup_card',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='card_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup_card.Popup_card'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_click',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='card_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup_card.Popup_card'),
        ),
    ]
