# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_card', '0008_auto_20170924_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commend_related',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
