# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseentity',
            name='priority_order',
            field=models.IntegerField(default=100),
        ),
    ]
