# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseEntity')),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('gender', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='+birth_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.baseentity', models.Model),
        ),
    ]
