# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 01:10
from __future__ import unicode_literals

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(upload_to=apps.user.models.user_directory_path),
        ),
    ]
